image: docker:19

services:
  - docker:docker:19

stages:
  - build
  - deploy

gradle-build:
  image: gradle:latest
  stage: build
  script: "gradle clean jar"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == "master"