image:
  name: docker/compose:1.22.0 # update tag to whatever version you want to use.
  entrypoint: ["/bin/sh", "-c"]

stages:
  - build
  - deploy

gradle-build:
  image: gradle:latest
  stage: build
  script: "gradle clean jar"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

deploy:
  image: docker/compose:1.22.0
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == "master"