image:
  name: docker/compose:1.22.0
  entrypoint: ["/bin/sh", "-c"]
stages:
  - build
  - deploy

gradle-build:
  image: gradle:latest
  stage: build
  script:
    - "gradle clean"
    - "gradle copyJarToRoot"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

deploy:
  stage: deploy
  script:
    - docker-compose down
    - docker-compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == "master"