stages:
  - build
  - deploy

gradle-build:
  image: gradle:latest
  stage: build
  script:
    - "gradle clean"
    - "gradle bootJar"
  artifacts:
    paths:
      - build/libs/test_task_S7-1.0-SNAPSHOT.jar
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

deploy:
  image: openjdk:latest
  stage: deploy
  script:
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    docker-compose up -d --build
    echo "Success"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"