image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

stages:
  - build
  - deploy

gradle-build:
  image: gradle:latest
  stage: build
  script: "gradle clean jar"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

deploy:
  stage: deploy
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose down
    - docker-compose up -d
  rules:
    - if: $CI_COMMIT_BRANCH == "master"