version: '0.1'

services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432

  app:
    build: .
    volumes:
      - ./:/app
    container_name: app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_URL=jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080

