spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/s7
    password: root
    username: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
        dialect:

jwt:
  token:
    secret: jwtAuth
    expired: 3600000

logging:
  level:
    root: INFO
  file:
    name: logback.log
    path: /