spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres #${POSTGRES_URL}
    password: postgres #${POSTGRES_PASSWORD}
    username: root #${POSTGRES_USER}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  token:
    secret: jwtAuth
    expired: 3600000

logging:
  level:
    root: INFO
  file:
    name: logback.log
    path: /